version: '3'
services:

  respondor:
    container_name: respondor
    image: respondor:latest
    build:
      context: .
    depends_on:
      - postgis
    volumes:
      - ./config.ini:/config.ini
      - ./data:/data
    ports:
      - '5000:5000'
  
  postgis:
    container_name: postgis
    image: postgis/postgis:13-master
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=respondor
